-- Named rapids within a reach.
-- AI-seeded initially; community corrections and maintainer verification over time.
-- A class 5 kayaker should recognize these names immediately — accuracy > completeness.
CREATE TABLE rapids (
    id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    reach_id                UUID        NOT NULL REFERENCES reaches(id) ON DELETE CASCADE,

    name                    TEXT        NOT NULL,
    river_mile              NUMERIC(5,2),           -- distance from put-in; null = unknown
    location                GEOGRAPHY(POINT, 4326), -- point on the river; null = unknown

    -- Difficulty (YSS scale with .5 increments; 6.0 = unrunnable)
    class_rating            NUMERIC(3,1),           -- typical/moderate flows
    class_at_low            NUMERIC(3,1),
    class_at_high           NUMERIC(3,1),

    description             TEXT,                   -- beta: lines, hazards, what to scout
    portage_description     TEXT,                   -- null = no known portage
    is_portage_recommended  BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Data provenance and verification
    -- 'ai_seed'   = generated by AI batch seeder, treat as draft
    -- 'community' = submitted by a user from their device
    -- 'import'    = bulk imported from a known dataset
    -- 'maintainer'= entered or confirmed by a project maintainer
    data_source     TEXT        NOT NULL DEFAULT 'ai_seed'
                                CHECK (data_source IN ('ai_seed','community','import','maintainer')),
    ai_confidence   SMALLINT    CHECK (ai_confidence BETWEEN 0 AND 100),
    verified        BOOLEAN     NOT NULL DEFAULT FALSE,
    verified_at     TIMESTAMPTZ,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX rapids_reach_id_idx   ON rapids (reach_id);
CREATE INDEX rapids_river_mile_idx ON rapids (reach_id, river_mile);
CREATE INDEX rapids_location_idx   ON rapids USING GIST (location);
CREATE INDEX rapids_verified_idx   ON rapids (reach_id) WHERE verified = TRUE;

-- Trigger to keep updated_at current
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER rapids_updated_at
    BEFORE UPDATE ON rapids
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
