<template>
  <UTooltip :text="tooltipText" :ui="{ width: 'max-w-xs' }">
    <span
      class="inline-flex items-center gap-1 rounded-full px-1.5 py-0.5 text-xs font-medium cursor-default select-none"
      :class="badgeClass"
    >
      <span>{{ icon }}</span>
      <span>{{ label }}</span>
    </span>
  </UTooltip>
</template>

<script setup lang="ts">
import { computed } from 'vue'

// ---- Types ------------------------------------------------------------------

type Source =
  | 'usgs'
  | 'dwr'
  | 'manual'
  | 'ai_seed'
  | 'ai_web'
  | 'community'

// ---- Props ------------------------------------------------------------------

const props = defineProps<{
  source:      Source
  verified?:   boolean
  confidence?: number  // 0–100, only meaningful for AI sources
  verifiedAt?: string  // ISO date string
  size?:       'xs' | 'sm'
}>()

// ---- Derived display --------------------------------------------------------

/**
 * Display name hierarchy:
 *   verified always takes precedence — a community entry confirmed by 12 paddlers
 *   is more trustworthy than an old staff entry. Source is secondary context.
 */
const label = computed(() => {
  if (props.source === 'usgs') return 'USGS'
  if (props.source === 'dwr')  return 'DWR'

  if (props.verified) {
    if (props.source === 'manual')    return 'Verified'
    if (props.source === 'ai_web')    return 'AI verified'
    if (props.source === 'ai_seed')   return 'AI verified'
    if (props.source === 'community') return 'Community verified'
  }

  if (props.source === 'manual')    return 'Staff entry'
  if (props.source === 'ai_web')    return 'AI draft'
  if (props.source === 'ai_seed')   return 'AI draft'
  if (props.source === 'community') return 'Community'
  return 'Unknown'
})

const icon = computed(() => {
  if (props.source === 'usgs' || props.source === 'dwr') return '📡'
  if (props.source === 'manual') return props.verified ? '✓' : '✎'
  if (props.source === 'ai_seed' || props.source === 'ai_web') return '✦'
  if (props.source === 'community') return '◎'
  return '·'
})

const badgeClass = computed(() => {
  if (props.source === 'usgs' || props.source === 'dwr') {
    return 'bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-300'
  }
  if (props.verified) {
    if (props.source === 'community') {
      return 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300'
    }
    return 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300'
  }
  if (props.source === 'ai_seed' || props.source === 'ai_web') {
    return 'bg-violet-50 text-violet-600 dark:bg-violet-950 dark:text-violet-300'
  }
  if (props.source === 'community') {
    return 'bg-amber-50 text-amber-600 dark:bg-amber-950 dark:text-amber-300'
  }
  return 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400'
})

const tooltipText = computed(() => {
  const lines: string[] = []

  // Source description
  const sourceDesc: Record<Source, string> = {
    usgs:      'Real-time sensor data from the U.S. Geological Survey.',
    dwr:       'Real-time sensor data from the Colorado Division of Water Resources.',
    manual:    'Entered by the H2OFlows team.',
    ai_seed:   'Generated by AI from training data — published guidebooks, American Whitewater, and trip reports.',
    ai_web:    'Generated by AI cross-referenced with current American Whitewater and other online sources.',
    community: 'Submitted by a paddler in the H2OFlows community.',
  }
  lines.push(sourceDesc[props.source] ?? 'Source unknown.')

  // Confidence
  if (props.confidence != null && (props.source === 'ai_seed' || props.source === 'ai_web')) {
    lines.push(`AI confidence: ${props.confidence}%`)
  }

  // Verification
  if (props.verified) {
    const when = props.verifiedAt
      ? ` (${new Date(props.verifiedAt).toLocaleDateString()})`
      : ''
    lines.push(`Verified${when}.`)
  } else if (props.source !== 'usgs' && props.source !== 'dwr') {
    lines.push('Not yet independently verified — treat with appropriate caution.')
  }

  return lines.join(' ')
})
</script>
